baseURL = 'https://www.brunomikoski.com/portifolio'
languageCode = 'en-US'
title = 'Bruno Mikoski - Software Engineer'

[[menus.main]]
name = 'All Works'
pageRef = '/all-works'
weight = 10

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 20

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"
